<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>USER REPORT</title>
        <link rel="stylesheet" href="css/print-layouts.css">
    </head>

    <body>
        <div class="page" size="A4">

    <!-- TOP SECTION -->
            <div class="top-section">
                <div class="address">
                    <div class="address-content">
                        <h2> PISA</h2>
                        <p>123 Fifth Avenue, New York, NY 10160</p>
                    </div>
                </div>
                <div class="contact">
                    <div class="contact-content">
                        <div class="email"> Email: 
                            <span class="span">
                                contact@info.com
                            </span>
                        </div>
                        <div class="number"> Number: 
                            <span class="span">
                                929-242-6868
                            </span>
                        </div>
                    </div>
                </div>
            </div>

    <!-- USER REPORT -->
            <div class="user-report">
                <div class="title">
                    User Report
                </div>
                <div class="des">
                    <p class="code">
                        #CODENUMBERHERE
                    </p>
                    <p class="issue"> Issued: <span> Dept. 12, 2023</span></p>
                </div>
            </div>

    <!-- GENERATED BY -->
            <div class="generated-by">
                <div class="title">
                    Generated By
                </div>
                <div class="gen-sec">
                    <div class="name">
                        Jonathan Doe
                    </div>
                    <p>User ID: T16922_9</p>
                    <p>jonathandoe@gmail.com</p>
                </div>

                <div class="gen-sec">
                    <div class="sub-title"> Account Information </div>
                    <div class="user-info">
                        <p>Role: Teacher</p>
                        <p>Username: john_doe</p>
                    </div>
                </div>
            </div>

    <!-- REPORT TABLE -->
        <div class="table">
            <table id="report-table">
                    <tr>
                        <th>Teacher ID</th>
                        <th>Full Name</th>
                        <th>Email</th>
                        <th>Username</th>
                        <th>Status</th>
                    </tr>
                    <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>
                </table>
            </div>


        </div>
    </body>
</html>